// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt_Int = require("bs-platform/lib/js/belt_Int.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Dices$JoaDicesRescript = require("./Dices.bs.js");

function parseCLI(command) {
  var attack = {
    contents: /* [] */0
  };
  var defense = {
    contents: /* [] */0
  };
  var isDefense = {
    contents: false
  };
  var partialInt = {
    contents: ""
  };
  var addDice = function (dice) {
    var times = Belt_Int.fromString(partialInt.contents);
    var times$1 = times !== undefined ? times : 1;
    partialInt.contents = "";
    if (isDefense.contents) {
      defense.contents = Belt_List.concat(defense.contents, Dices$JoaDicesRescript.roll(times$1, dice));
    } else {
      attack.contents = Belt_List.concat(attack.contents, Dices$JoaDicesRescript.roll(times$1, dice));
    }
    
  };
  Belt_Array.forEach(Array.from(command, (function (s) {
              return s;
            })), (function (c) {
          var other = c.toUpperCase();
          switch (other) {
            case " " :
                return ;
            case "+" :
                isDefense.contents = false;
                return ;
            case "-" :
                isDefense.contents = true;
                return ;
            case "0" :
            case "1" :
            case "2" :
            case "3" :
            case "4" :
            case "5" :
            case "6" :
            case "7" :
            case "8" :
            case "9" :
                break;
            case "D" :
                return addDice(Dices$JoaDicesRescript.doomDice);
            case "G" :
                return addDice(Dices$JoaDicesRescript.giganticDice);
            case "N" :
                return addDice(Dices$JoaDicesRescript.blackDice);
            case "R" :
                return addDice(Dices$JoaDicesRescript.redDice);
            case "B" :
            case "W" :
                return addDice(Dices$JoaDicesRescript.whiteDice);
            case "J" :
            case "Y" :
                return addDice(Dices$JoaDicesRescript.yellowDice);
            default:
              console.log(other, "is invalid, example: 3R W - 2Y");
              return ;
          }
          partialInt.contents = partialInt.contents + c;
          
        }));
  console.log({
        attack: Dices$JoaDicesRescript.toString(attack.contents),
        defense: Dices$JoaDicesRescript.toString(defense.contents),
        result: Dices$JoaDicesRescript.toString(Dices$JoaDicesRescript.fight(attack.contents, defense.contents))
      });
  
}

parseCLI("+1WG -BG");

var _FRENCH_SYNTAX = true;

exports._FRENCH_SYNTAX = _FRENCH_SYNTAX;
exports.parseCLI = parseCLI;
/*  Not a pure module */
