// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Dices$JoaDicesRescript = require("./Dices.bs.js");

function log(prim) {
  console.log(prim);
  
}

console.log("\n> 1 red");

var prim = Dices$JoaDicesRescript.toString(Dices$JoaDicesRescript.roll(3, Dices$JoaDicesRescript.redDice));

console.log(prim);

console.log("\n> 3 red, 2 yellow");

var prim$1 = Dices$JoaDicesRescript.toString(Belt_List.concat(Dices$JoaDicesRescript.roll(3, Dices$JoaDicesRescript.redDice), Dices$JoaDicesRescript.roll(2, Dices$JoaDicesRescript.yellowDice)));

console.log(prim$1);

var attack = Dices$JoaDicesRescript.roll(4, Dices$JoaDicesRescript.redDice);

console.log("\n> attack");

var prim$2 = Dices$JoaDicesRescript.toString(attack);

console.log(prim$2);

var defense = Dices$JoaDicesRescript.roll(5, Dices$JoaDicesRescript.yellowDice);

console.log("\n> defense");

var prim$3 = Dices$JoaDicesRescript.toString(defense);

console.log(prim$3);

console.log("\n> fight");

var prim$4 = Dices$JoaDicesRescript.toString(Dices$JoaDicesRescript.fight(attack, defense));

console.log(prim$4);

var concat = Belt_List.concat;

exports.log = log;
exports.concat = concat;
exports.attack = attack;
exports.defense = defense;
/*  Not a pure module */
